sudo: required
services: 
    - docker

before_install:
    - docker build -t ssccljh/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run jlei/react-test npm test -- --coverage

after_success:
    - docker build -t ssccljh/multi-client ./client
    - docker build -t ssccljh/multi-nginx ./nginx
    - docker build -t ssccljh/multi-server ./server
    - docker build -t ssccljh/multi-worker ./worker
    # login into the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # take those images and push them to docker hub
    - docker push ssccljh/multi-client
    - docker push ssccljh/multi-nginx
    - docker push ssccljh/multi-server
    - docker push ssccljh/multi-worker